config/routes.rb
Inkblot::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    resources :projects
    root "projects#index"
  end
  unauthenticated :user do
    devise_scope :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	cattr_accessor :genres do
    ['Science Fiction','Romance', "Fantasy", "Humour", "Mystery", "Paranormal", "Thriller", "Horror", "Action", "Adventure", "Historical Fiction", "Teen Fiction", "Fan Fiction", "Poetry", "Short Story","Chick Lit", "Spiritual","Non Fiction","Biography","Essay", "Young Adult" ].sort.push('Other')
  end
  cattr_accessor :ratings do
  	['G: General Audiences', 'PG: Parental Guidance Suggested', 'PG-13: Parents Strongly Cautioned', 'R: Restricted', 'NC-17']
  end
  validates :title, presence: true, length: { minimum: 1}
  validates :text, presence: true, length: {minimum: 1}

  mount_uploader :image, CoverartUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :profile_image, ProfileImageUploader

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username, uniqueness: { case_sensitive: false }

  # Override for Devise to allow username OR email to auth
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  # Facebook Omniauth
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(name: auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid: auth.uid,
                         email: auth.info.email,
                         biography: auth.info.description,
                         location: auth.info.location,
                         username: auth.info.nickname,
                         password: Devise.friendly_token[0,20]
                         # TODO profile image # http://stackoverflow.com/questions/14009745/railscarrierwave-with-omniauth # key = :image
                        )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :username, :email, :password, :current_password, :profile_image) }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@projects = Project.all
  end
  def new
  	@project = Project.new
  end
  def create 
  	@project = Project.new(project_params)
  	if @project.save
  		redirect_to @project
  	else
  		render 'new'
  	end

  end
    def show
	@project = Project.find(params[:id])  	
  end
def edit
	@project = Project.find(params[:id])
end
def update
	@project = Project.find(params[:id])
	if @project.update(params[:project].permit(:title, :text, :genre, :rating, :language, :image))
		redirect_to @project
		else
			render 'edit'
		end
	end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
  	params.require(:project).permit(:title, :text, :genre, :rating, :language, :image)
  	
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path, options = {})
    class_name = "btn btn-primary"
    class_name += current_page?(link_path) ? ' active' : ''

    options = {class: class_name}.merge(options)

    content_tag(:li) do
      link_to link_text, link_path, options
    end
  end

end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    output = ''
    flash.each do |type, message|
      next if message.blank?
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)
      output += flash_container(type, message)
    end

    raw(output)
  end

  def flash_container(type, message)
    raw(content_tag(:div, :class => "alert alert-#{type}") do
      content_tag(:a, raw("&times;"),:class => 'close', :data => {:dismiss => 'alert'}) +
      message
    end)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inkblot</title>
  <%= favicon_link_tag       "inkdrop.png", type: "image/png" %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if user_signed_in? %>
    <div class="row" id="global-header-row">
      <p class="text-center">
        <embed src="<%= asset_path("inkblotlogoheader.svg") %>" width="100" height="120"/>
      </p>
    </div>
    <div class="row" id="global-content-row">
      <div id="global-navigation" class="col-md-3">
        <%= render "shared/navigation" if user_signed_in? %>
      </div>

      <div id="global-content" class="col-md-8 col-md-offset-1">
    <% end %>
        <%= bootstrap_flash %>

        <%= yield %>
    <% if user_signed_in? %>
      </div>
    </div>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/projects/edit.html.erb
<h1>edit story</h1>
<%= form_for @project, url: project_path(@project), method: :patch,  :html => { :multipart => true }  do |f| %>
 <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited
      this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<p> 
	<%= f.text_field :title, placeholder: 'Title' %>
</p>
<p> <%= f.label :genre %>
    <%= f.select :genre, options_for_select(Project.genres) %>
</p>
<p>
	<%= f.label :rating %>
	<%= f.select :rating, options_for_select(Project.ratings) %>
</p>
<p>
	<%= f.label :language %>
	 <%= f.select :language, options_from_collection_for_select(LanguageList::COMMON_LANGUAGES.sort, "name", "name") %>
</p>
<p>
	<%= f.text_area :text %>
</p>

<p> <%= f.file_field :image %></p>
<%= f.submit %>
<% end %>
<%= link_to 'Back', project_path %>

app/views/projects/index.html.erb
<div id="posts">
<%= link_to "New Project", new_project_path %>

<h1>All Stories</h1>
<% @projects.each do |project| %>
<h3><%= link_to project.title, project_path(project) %></h3>
<% end %>
</div>

app/views/projects/new.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>

 <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited
      this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<p> 
	<%= f.text_field :title, placeholder: 'Title' %>
</p>
<p> <%= f.label :genre %>
    <%= f.select :genre, options_for_select(Project.genres) %>
</p>
<p>
	<%= f.label :rating %>
	<%= f.select :rating, options_for_select(Project.ratings) %>
</p>
<p>
	<%= f.label :language %>
	 <%= f.select :language, options_from_collection_for_select(LanguageList::COMMON_LANGUAGES.sort, "name", "name") %>
</p>
<p>
	<%= f.text_area :text %>
</p>

<p> <%= f.file_field :image %></p>
<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1> <%= @project.title %> </h1>
<p> <small><%= @project.language %>, <%= @project.rating %>, <%= @project.genre %> 
<strong><%= link_to 'Edit', edit_project_path(@project) %> | 
<%= link_to 'Destroy', project_path(@project), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' } %> </strong></small>
<p><%= @project.text %></p>
<div id="coverphoto">
	<%= image_tag @project.image_url %>
</div>

app/views/shared/_navigation.html.erb
<div>
  <ul class="nav nav-pills nav-stacked">
    <li>
      <%= image_tag current_user.profile_image_url, class: "circle-image", id: "profile-image" %>
    </li>
    <%= nav_link("MY WRITING", "#") %>
    <%= nav_link "FRIENDS", "#" %>
    <%= nav_link "BOOKSHELF", "#" %>
    <%= nav_link "ACCOUNT", edit_user_registration_path %>
    <%= nav_link "LOGOUT", destroy_user_session_path, method: :delete %>
  </ul>
</div>